export const JOKES = {
  "Dad jokes": [
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I'm afraid for the calendar. Its days are numbered.",
    "What do you call a fake noodle? An impasta!",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "I used to hate facial hair, but then it grew on me.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don't scientists trust atoms? Because they make up everything.",
    "How does a penguin build its house? Igloos it together!",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "What do you call a fish with no eyes? A fsh.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the P is silent.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  ],
  Puns: [
    "I wondered why the baseball was getting bigger. Then it hit me.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "I used to be a banker, but I lost interest.",
    "The baker quit because he wasn't making enough dough.",
    "I told my suitcase there would be no vacation this year. Now I'm dealing with emotional baggage.",
    "The math book looked sad because it had too many problems.",
    "I got hit in the head with a can of soda. Luckily it was a soft drink.",
    "The graveyard is so popular, people are dying to get in.",
    "I used to play piano by ear, but now I use my hands.",
    "The electrician was shocked by how his business was doing.",
    "I made a pencil with two erasers. It was pointless.",
    "The lumberjack was a great musician. He had perfect chopsticks.",
    "I tried to catch fog yesterday. Mist.",
    "The dentist and the manicurist fought tooth and nail.",
    "I used to be addicted to soap, but I'm clean now.",
    "The circus fire was intense. It was in tents.",
    "A chicken crossing the road is poultry in motion.",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
  ],
  "One-liners": [
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I haven't slept for ten days, because that would be too long.",
    "I used to think I was indecisive, but now I'm not so sure.",
    "The early bird might get the worm, but the second mouse gets the cheese.",
    "I threw a boomerang a few years ago. I now live in constant fear.",
    "My therapist says I have a preoccupation with vengeance. We'll see about that.",
    "I have the heart of a lion and a lifetime ban from the zoo.",
    "I told my computer I needed a break, and now it won't stop sending me Kit-Kat ads.",
    "I'm on a whiskey diet. I've lost three days already.",
    "I used to hate facial hair, but then it grew on me.",
    "The problem with kleptomaniacs is they take things literally.",
    "I haven't talked to my wife in three weeks. I didn't want to interrupt her.",
    "I have a split personality. Me and myself disagree on everything.",
    "I'm reading a horror story in Braille. Something bad is about to happen — I can feel it.",
    "I asked the librarian if the library had books on paranoia. She whispered, 'They're right behind you.'",
    "My wallet is like an onion. When I open it, it makes me cry.",
  ],
  "Knock-knock": [
    "Knock knock. Who's there? Lettuce. Lettuce who? Lettuce in, it's cold out here!",
    "Knock knock. Who's there? Boo. Boo who? Don't cry, it's just a joke!",
    "Knock knock. Who's there? Cow says. Cow says who? No, cow says moo!",
    "Knock knock. Who's there? Tank. Tank who? You're welcome!",
    "Knock knock. Who's there? Atch. Atch who? Bless you!",
    "Knock knock. Who's there? Olive. Olive who? Olive you!",
    "Knock knock. Who's there? Harry. Harry who? Harry up and answer the door!",
    "Knock knock. Who's there? Interrupting cow. Interrupting cow wh— MOOO!",
    "Knock knock. Who's there? Alpaca. Alpaca who? Alpaca the suitcase, you load the car!",
    "Knock knock. Who's there? Banana. Banana who? Knock knock. Who's there? Banana. Banana who? Knock knock. Who's there? Orange. Orange who? Orange you glad I didn't say banana?",
    "Knock knock. Who's there? Wooden shoe. Wooden shoe who? Wooden shoe like to hear another joke?",
    "Knock knock. Who's there? Cereal. Cereal who? Cereal pleasure to meet you!",
    "Knock knock. Who's there? Justin. Justin who? Justin time for dinner!",
    "Knock knock. Who's there? Dishes. Dishes who? Dishes the police, open up!",
    "Knock knock. Who's there? Nobel. Nobel who? Nobel, that's why I knocked!",
    "Knock knock. Who's there? Luke. Luke who? Luke through the peephole and find out!",
    "Knock knock. Who's there? Ice cream. Ice cream who? Ice cream if you don't let me in!",
    "Knock knock. Who's there? Howard. Howard who? Howard I know you're in there!",
  ],
  Observational: [
    "Why is it called 'after dark' when it's really after light?",
    "The word 'bed' looks like a bed. The word 'shark' looks nothing like a shark. English is weird.",
    "Adults are just kids who've been alive longer.",
    "If you clean your room, you find stuff you forgot you had. If you don't clean, you can't find anything. There's no winning.",
    "The snooze button is the most optimistic button on your phone.",
    "Nothing makes you feel old like hearing a song you loved in a grocery store.",
    "Why do we drive on a parkway and park on a driveway?",
    "The first person to eat a pineapple must have been very confident.",
    "Autocorrect has become my worst enema.",
    "Why is it called a building if it's already built?",
    "You never realize how boring your wall is until you're staring at it waiting for food to heat up.",
    "The most unrealistic thing about cartoons is how nobody ever closes a door.",
    "I love how 'sleep in' and 'sleep on' mean completely different things.",
    "Every time I lose weight, I find it again in the kitchen.",
    "Why do we say 'tuna fish' but not 'beef mammal'?",
    "The gym is the only place where you hear 'good job' from strangers while sweating and suffering.",
    "Nothing is more suspicious than a transparent bag of chips.",
    "School teaches you that you can fail at life even if you know the answers.",
  ],
  "Programming / tech": [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "There are only 10 types of people: those who understand binary and those who don't.",
    "A SQL query walks into a bar, walks up to two tables, and asks: 'Can I join you?'",
    "Why did the developer go broke? Because he used up all his cache.",
    "I would tell you a UDP joke, but you might not get it.",
    "How many programmers does it take to change a light bulb? None — that's a hardware problem.",
    "Why do Java developers wear glasses? Because they don't C#.",
    "A programmer's wife says: 'Go to the store and get a loaf of bread. If they have eggs, get a dozen.' He comes home with 12 loaves of bread.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "There are two hard things in programming: cache invalidation, naming things, and off-by-one errors.",
    "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
    "I told my computer a joke about recursion. It got the joke. And the joke. And the joke.",
    "What's a programmer's favorite hangout place? Foo Bar.",
    "Why do programmers confuse Halloween and Christmas? Because Oct 31 equals Dec 25.",
    "A QA engineer walks into a bar. Orders 1 beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. First real customer walks in and asks where the bathroom is. The bar bursts into flames.",
    "Why did the developer get stuck in the shower? The instructions said: lather, rinse, repeat.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why did the web developer leave the restaurant? Because of the table layout.",
  ],
  Science: [
    "Never trust an atom. They make up everything.",
    "Why can't you trust an atom? Because they literally make up everything!",
    "What did the biologist wear to impress his date? Designer genes.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Einstein developed a theory about space. And it was about time too.",
    "What is a computer's favorite snack? Microchips!",
    "Why did the germ cross the microscope? To get to the other slide.",
    "What did the proton say to the electron? Stay positive!",
    "Why are chemists excellent at solving problems? They have all the solutions.",
    "What do you do with a sick chemist? If you can't helium and you can't curium, you might as well barium.",
    "Why did the photon check a hotel? Because it was travelling light.",
    "What did one ion say to the other? I've got my ion you.",
    "Why can't you trust gravity? It's always pulling you down.",
    "What did the DNA say to the other DNA? Do these genes make me look fat?",
    "Why did the plant get in trouble? It was photosynthesizing in class.",
    "What is a physicist's favorite food? Fission chips.",
    "Why did the astronaut break up with the moon? It was just a phase.",
    "What did the volcano say to the mountain? I lava you!",
  ],
  "Dark humor": [
    "I have a joke about trick-or-treating, but I'll save it for Halloween.",
    "My calendar is always full. It has a lot of dates.",
    "I told my computer I needed a break. It said: 'No problem, I'll go to sleep mode.'",
    "I asked my dog what's two minus two. He said nothing.",
    "I'm great at multitasking. I can procrastinate and worry at the same time.",
    "My bed and I are perfect for each other, but my alarm clock keeps trying to break us up.",
    "I have a joke about construction, but I'm still working on it.",
    "I used to be a baker, but I couldn't make enough dough.",
    "My fear of elevators is growing on several levels.",
    "I told my suitcase we're not going on vacation this year. Now I'm dealing with emotional baggage.",
    "I have a stepladder because my real ladder left when I was just a kid.",
    "I'm afraid of speed bumps, but I'm slowly getting over it.",
    "I ordered a chicken and an egg online. I'll let you know which comes first.",
    "My laziness is like a superpower. I can nap through anything.",
    "I have a joke about time travel, but you didn't like it.",
    "I tried to organize a hide-and-seek tournament, but good players are hard to find.",
    "My plants and I have an understanding. I don't bother them, and they slowly die anyway.",
    "I have a split personality. We both agree I'm hilarious.",
  ],
  Riddles: [
    "What has hands but can't clap? A clock.",
    "What has a head and a tail but no body? A coin.",
    "What gets wetter the more it dries? A towel.",
    "What can you catch but not throw? A cold.",
    "What has keys but can't open locks? A piano.",
    "What has a neck but no head? A bottle.",
    "What goes up but never comes down? Your age.",
    "What has to be broken before you can use it? An egg.",
    "What has legs but doesn't walk? A table.",
    "What can travel around the world while staying in a corner? A stamp.",
    "What is full of holes but still holds water? A sponge.",
    "What gets bigger the more you take away? A hole.",
    "What has one eye but can't see? A needle.",
    "What goes through cities and fields but never moves? A road.",
    "What has words but never speaks? A book.",
    "What runs but never walks? Water.",
    "What has a thumb and four fingers but is not alive? A glove.",
    "What comes down but never goes up? Rain.",
    "I speak without a mouth and hear without ears. What am I? An echo.",
    "The more of this there is, the less you see. What is it? Darkness.",
    "What can fill a room but takes up no space? Light.",
    "What has cities but no houses, forests but no trees? A map.",
    "What belongs to you but other people use it more? Your name.",
    "What kind of coat is always wet? A coat of paint.",
    "What has a bottom at the top? Your legs.",
    "What can you hold in your left hand but not in your right? Your right elbow.",
    "What has many teeth but cannot bite? A comb.",
    "What building has the most stories? A library.",
    "What goes up and down but doesn't move? Stairs.",
    "What has a ring but no finger? A telephone.",
  ],
};

const decks = new Map();

function shuffle(list) {
  const copy = [...list];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function pickJoke(genre) {
  const list = JOKES[genre];

  if (!list || list.length === 0) {
    return null;
  }

  if (list.length === 1) {
    return list[0];
  }

  let deck = decks.get(genre);
  if (!deck || deck.length === 0) {
    deck = shuffle(list);
    decks.set(genre, deck);
  }

  return deck.pop();
}
